spesmilo/electrumx

electrumx/lib/coins.py, electrumx/lib/tx.py, electrumx/server/db.py, tests/server/test_mempool.py
This provides much better performance over plain namedtuple on cpython for the things we're constructing and transporting a lot of: txes, inputs, and outputs. It might be a little more readable.
This is inspired by earlier experiments by @ofek and benchmarks by @erasmospunk in kyuupichan/electrumx#150.
=> Use slotted dataclasses instead of namedtuples.

docs/HOWTO.rst, docs/PERFORMANCE-NOTES, electrumx/lib/util.py, electrumx/server/daemon.py, electrumx/server/peers.py, electrumx/server/session.py, setup.py, tests/server/test_daemon.py
This adds ujson and python-rapidjson support. If either are found in the Python environment, they are used instead of the stdlib json library where possible. To ease installation of a compatible version of either library, "ujson" and "rapidjson" extras strings are available for the install:
pip3 install .[rapidjson]
This was work was split from spesmilo/electrumx#10.
=> Support rapidjson and ujson libs for better sync performance.

electrumx/server/peers.py
If already in peer list but with different ports, don't ignore.
Also, add a comment to explain how changing ports are handled as it is really non-trivial...
=> local RPC add_peer: retry if given different ports

docs/environment.rst, electrumx/server/env.py, electrumx/server/session.py, tests/server/test_env.py
One can deny serving some specific client versions via DROP_CLIENT. However, there is no way to deny serving clients, which do not identify themselves at all. This patch adds an option to do that. If DROP_CLIENT_UNKNOWN is set, the server will drop connections on a first method call (other than server.version) if the client is unknown.
Let me know what you think. I am running this fork in production myself.
---
This was originally submitted as kyuupichan/electrumx#1016, but I don't know what the future of that repo is, so submitting here as well, just in case.
=> Add option to deny serving unknown clients

docs/protocol-methods.rst
The docs and the actual behaviour are inconsistent. Which one do we fix?
The Electrum client expects the current behaviour, so we fix the docs.
see https://github.com/spesmilo/electrumx/blob/10616105b9ca2fc013dd3b0efbc46db7e847a382/electrumx/server/session.py#L1084-L1089
=> docs: fix blockchain.scripthash.get_balance return value

electrumx/server/peers.py
If a peer fails to respond to `server.version` or `server.add_peer` calls, mark as bad. RPC sessions from aiorpcx that have closed have their send methods raise `asyncio.CancelledError`, which we catch in this case.
This is a candidate fix for spesmilo/electrumx#19.
=> Mark peer bad when RPC session is canceled during critical requests.

electrumx/server/db.py
We call the .clear method on them which is not supported in the more abstract `Sequence` type.
=> FlushData.undo_infos and FlushData.deletes are lists

docs/rpc-interface.rst, electrumx/server/session.py
Removes time-based groups, because they are ineffective and in fact prevent the usage of anti-ddos mechanisms. Fixes #26
=> Remove time-based groups

electrumx/lib/coins.py
We need at least one IPv6 host running. It is mine 👍
=> Added IPv6-only litecoin testnet electrum instance

electrumx/lib/coins.py
The ESTIMATE_FEE of Primecoin is changed to 1, instead of 1.024
=> Adjust Primecoin ESTIMATE_FEE

contrib/Dockerfile
Based on the official Python-on-debian images instead of Ubuntu base.
Unfortunately is a little less readable than the existing one due to having two stages: a build stage based on the thick debian buster Python image and a runtime stage based on the slim debian buster Python image.
Takes the final image size down from 485 MB to 165 MB.
=> Slimmer docker image. Also uses PyPI instead of GitHub for the package

electrumx/lib/coins.py
It is no longer appropriate to call BCH "Bitcoin Cash ABC", even for convenience; this PR reflects that. Also updates default server list.
=> Fix BCH entry in coins.py

electrumx/lib/coins.py
Includes some IP addresses, because Namecoin is intended to be an alternative to the DNS; thus it would be highly unfortunate if a DNS outage caused a Namecoin outage.
=> Namecoin: add more peers

docs/release_process.txt, electrumx/__init__.py, setup.py
- avoid hardcoding version number in `setup.py`, instead get it programmatically
- expose `__version__` field in main module, as is standard practice
=> setup.py: de-dupe version number, and expose `__version__` in module

contrib/Dockerfile
Docker image [3.9.4-buster](https://hub.docker.com/_/python/tags?page=1&name=3.9.4-buster) is affected by many vulnerabilities.
This PR updates the Dockerfile upgrading to `python:3.9.16-bullseye` and `librocksdb6.11`
=> upgrade Docker image to 3.9.16-bullseye to solve vulnerabilities

.cirrus.yml, docs/HOWTO.rst, electrumx/lib/coins.py, setup.py
`x11_hash` had no updates since 2015. `dash_hash` is actively maintained (supports Python3.10 for example).
=> chore: switch from no longer maintained x11_hash to dash_hash

docs/HOWTO.rst, electrumx/lib/lrucache.py, electrumx/server/session.py, requirements.txt
closes https://github.com/spesmilo/electrumx/issues/247
=> dependencies: rm "pylru" dep, instead inline stripped-down "cachetools"

electrumx/lib/coins.py
No peers were still working so updating with fresh ones. For security and anti sybil reasons not all old peers were removed, just some working ones added.
=> Add some working peers for coin Namecoin

electrumx/server/controller.py, requirements.txt
Increase the allowed version of [aiorpcx](https://github.com/kyuupichan/aiorpcX) to the new 0.24 version, which uses the new websockets version, so it's possible to get rid of the websockets deprecation warning when starting electrumX.
Changelog of aiorpcX 0.24: [Changelog](https://github.com/kyuupichan/aiorpcX/blob/master/docs/changelog.rst#version-024-16-jan-2024)
=> Increase allowed aiorpcx version to 0.24

.gitignore, electrumx/server/daemon.py, electrumx/server/session.py, tests/server/test_daemon.py
Defines a protocol method ```blockchain.transaction.broadcast_package
``` for protocol version 1.4.4 and implements it so clients can submit a package of transactions to the mempool using the bitcoin core [```submitpackage```](https://bitcoincore.org/en/doc/27.0.0/rpc/rawtransactions/submitpackage/) method. This allows clients to broadcast a package of transactions that would on their own not be accepted to the mempool (e.g. below purge fee parent and high fee child to bump)
=> Implement method to submit package of transactions (submitpackage call)
